remove refs to vm_list.json

diff --git a/.github/workflows/reusable-test.yml b/.github/workflows/reusable-test.yml
--- a/.github/workflows/reusable-test.yml
+++ b/.github/workflows/reusable-test.yml
@@ -182,9 +182,7 @@ jobs:
       id: run_pre_test_command_self_hosted
       working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
       run: |
-        if ("${{ runner.name }}" -like "igklemen-runner-*") {
-          ${{env.PRE_COMMAND}} -SelfHostedRunnerName ${{ runner.name }}
-        }
+        ${{env.PRE_COMMAND}} -SelfHostedRunnerName ${{ runner.name }}
 
     # TODO: Clean up the combination of options: https://github.com/microsoft/ebpf-for-windows/issues/1590
     - name: Run test with Code Coverage in VS Dev environment
@@ -239,16 +237,19 @@ jobs:
 
     - name: Run post test command
       # Run the post test command even if the workflow has failed.
-      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true')
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && (inputs.environment != 'ebpf_cicd_tests')
       id: run_post_test_command
       working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
       run: |
-        if ("${{ runner.name }}" -like "igklemen-runner-*") {
-          ${{env.POST_COMMAND}} -SelfHostedRunnerName ${{ runner.name }}
-        }
-        else {
-          ${{env.POST_COMMAND}}
-        }
+        ${{env.POST_COMMAND}}
+
+    - name: Run post test command on self-hosted runner
+      # Run the post test command even if the workflow has failed.
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && (inputs.environment == 'ebpf_cicd_tests')
+      id: run_post_test_command_self_hosted
+      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+      run: |
+        ${{env.POST_COMMAND}} -SelfHostedRunnerName ${{ runner.name }}
 
     - name: Check for CodeCoverage
       if: steps.skip_check.outputs.should_skip != 'true'
